Intialize repository that crashes 'npm audit'
This repository crashes the following command:

    npm audit fix --workspaces --include-workspace-root --force

with the following error message:

    npm WARN audit Updating concurrently to 7.0.0,which is a SemVer major change.
    Exception in PromiseRejectCallback: Updating concurrently to 7.0.0,which is a SemVer major change.
    /home/otto/.volta/tools/image/npm/8.3.0/node_modules/@npmcli/arborist/lib/arborist/build-ideal-tree.js:1052
        return this[_buildDepStep]()

    RangeError: Maximum call stack size exceeded
    npm ERR! Maximum call stack size exceeded

    npm ERR! A complete log of this run can be found in:
    npm ERR!     /home/otto/.npm/_logs/2022-01-11T15_01_46_897Z-debug-0.log